version: "3.9"
services:
  app:
    image: app:latest
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile.prod

  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile.prod