version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_CONNECTION=${DB_CONNECTION_PROD}
      - DB_HOST=${DB_HOST_PROD}
      - DB_PORT=${DB_PORT_PROD}
      - DB_DATABASE=${DB_NAME_PROD}
      - DB_USERNAME=${DB_USER_PROD}
      - DB_PASSWORD=${DB_PASSWORD_PROD}

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ:-Asia/Tokyo}
    working_dir: /var/www/html

  db:
    build:
      context: .
      dockerfile: ./infra/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_NAME_PROD}
      MYSQL_USER: ${DB_USER_PROD}
      MYSQL_PASSWORD: ${DB_PASSWORD_PROD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD_PROD}
      TZ: 'Asia/Tokyo'
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: